// import Head from "next/head";
// import { Inter } from "@next/font/google";
// import React, { useEffect } from "react";

// import Ballpit from "./components/Ballpit";
// import SplitText from "./components/SplitText";

// const inter = Inter({ subsets: ["latin"] });

// export default function Home() {
//   return (
//     <div style={{ backgroundColor: "#fff" }} className={inter.className}>
//       <Head>
//         <title>Gaurav Burande</title>
//         <meta name="description" content="Generated by create next app" />
//         <meta name="viewport" content="width=device-width, initial-scale=1" />
//         <link rel="icon" href="/favicon.ico" />
//       </Head>
//       <SplitText
//         text="Hello, Tailwind!"
//         className="text-2xl font-semibold text-center"
//         delay={150}
//         animationFrom={{ opacity: 0, transform: "translate3d(0,50px,0)" }}
//         animationTo={{ opacity: 1, transform: "translate3d(0,0,0)" }}
//         easing="easeOutCubic"
//         threshold={0.2}
//         rootMargin="-50px"

//         // onLetterAnimationComplete={handleAnimationComplete}
//       />
//       {/* <div
//         style={{
//           position: "relative",
//           overflow: "hidden",
//           // minHeight: "500px",
//           // maxHeight: "500px",
//           width: "100%",
//         }}
//       >
//         <Ballpit
//           count={100}
//           gravity={0.7}
//           friction={0.8}
//           wallBounce={0.95}
//           followCursor={true}
//         />
//       </div> */}
//       {/* <WelcomePage></WelcomePage> */}
//     </div>
//   );
// }

import React from "react";
import SplitText from "./components/SplitText";

function index() {
  return (
    <div>
      <SplitText
        text="Hello, Tailwind!"
        className="text-2xl font-semibold text-center"
        delay={150}
        animationFrom={{ opacity: 0, transform: "translate3d(0,50px,0)" }}
        animationTo={{ opacity: 1, transform: "translate3d(0,0,0)" }}
        easing="easeOutCubic"
        threshold={0.2}
        rootMargin="-50px"

        // onLetterAnimationComplete={handleAnimationComplete}
      />
    </div>
  );
}

export default index;
