import Head from "next/head";
import { Inter } from "@next/font/google";
import React, { useEffect } from "react";
import styles from "../styles/Home.module.css";
import WelcomePage from "./WelcomePage";
import AOS from "aos";
import "aos/dist/aos.css";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  useEffect(() => {
    AOS.init({
      duration: 5000,
    });
  }, []);
  return (
    <>
      <Head>
        <title>Gaurav Burande</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <WelcomePage></WelcomePage>
    </>
  );
}
